### PR TITLE
Fixed write if less than all pending bytes were written in one operation

### LINKED ISSUE #23: Warning: writing input events failed
When I run the script, I get this warning whenever I move a stick or press a button. The input appears to update, but do so slowly. I'm running as root.

Setup:

* Ubuntu Trusty x64 on Asus c300
* Mayflash GC adapter on Wii U mode
* SSB Gamecube Controller

### PR DESCRIPTION
**Pull request by Emill**
When I run the program, I get a lot of "Warning: writing input events failed" when I touch any button or stick on my controller but no events are received by my games.

I figured out the write code to uinput is not correct. This patch makes sure all data is written even if all data couldn't be written in a single write command.

This should fix #23.

### CODE REVIEW

File: wii-u-gc-adapter.c [hunk 1]
```diff
@@ -349,8 +349,16 @@ static void handle_payload(int i, struct ports *port, unsigned char *payload, st
...
       events[e_count].code = SYN_REPORT;
       e_count++;
-      if (write(port->uinput, events, sizeof(events[0]) * e_count) != (int)sizeof(events[0]) * e_count)
-         fprintf(stderr, "Warning: writing input events failed\n");
+      size_t to_write = sizeof(events[0]) * e_count;
+      size_t written = 0;
+      while (written < to_write) {
+         ssize_t write_ret = write(port->uinput, (const char*)events + written, to_write - written);
+         if (write_ret <= 0) {
+            fprintf(stderr, "Warning: writing input events failed, return value was %d\n", write_ret);
```
Comment (ToadKing) [inline wii-u-gc-adapter.c]: The error log should log `errno` so something meaningful can be read from it. Specially, with `strerror_r`.

Comment (Emill) [inline wii-u-gc-adapter.c]: Is it better now?

**Comment by ToadKing** [comment]
looks okay to merge, i'll probably want to go and replace some the fprintf error calls to use perror in the future, but that's for another PR
